version: "3.3"
services:
  redis:
    image: redis:alpine
    networks:
      - shared
  mongo:
    image: mongo:4.2.11
    volumes:
      - mongodata:/data/db
    ports:
      - "127.0.0.1:${MONGODB_PORT}:27017"
    networks:
      - shared
  server:
    image: nertivia/server
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file: .env
    networks:
      - shared
  client:
    image: nertivia/client
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    env_file: .env
    networks:
      - shared
  caddy:
    image: caddy:alpine
    hostname: cdn.localtest.me
    env_file: .env
    volumes:
      - "./cdn/ssl_certs:/ssl_certs"
      - "./cdn/public_html:/public_html"
      - "./cdn/Caddyfile:/etc/caddy/Caddyfile"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - shared
  php:
    image: php:fpm-alpine
    volumes:
      - "./cdn/public_html:/public_html"
    env_file: .env
    networks:
      - shared
  image-server:
    image: node:lts-alpine
    working_dir: /public_html/node
    command: sh -c "npm i && node app.js"
    volumes:
      - "./cdn/public_html:/public_html"
    ports:
      - "${CDN_PORT}:${CDN_PORT}"
    env_file: .env
    networks:
      - shared
volumes:
  mongodata:
networks:
  shared:
